server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn
    username: learn
    password: learn
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
logging:
  level:
    tomcat: INFO
    org.hibernate.type: INFO
    org:
      springframework:
        security: INFO
    root: INFO
    web: TRACE


#management:
#  endpoint:
#    beans:
#      enabled: true
#    loggers:
#      enabled: true




